const express = require("express");
const router = express.Router();
const authRoutes = require("./auth.routes");
const addressRoutes = require("./address.routes");
const cartypeRoutes = require("./cartype.routes");
const showcaseRoutes = require("./showcase.routes");
const userRoutes = require("./user.routes");
const serviceRoutes = require("./service.routes");
const addonsRoutes = require("./addons.routes");
const appSettingRoutes = require("./appsetting.routes");
const faqRoutes = require("./faq.routes");
const themeRoutes = require("./theme.routes");
const blogRoutes = require("./blog.routes");
const businessHourRoutes = require("./bushour.routes");
const userThemeRoutes = require("./usertheme.routes");
const promoCodeRoutes = require("./promocode.routes");
const bookingRoutes = require("./booking.routes");
const reviewRoutes = require("./review.routes");
const dashbordRoutes = require("./dashbord.routes");
const contentRoutes = require("./contect.routes");
const popupimageRouter = require("./popupimage.routes");

router.use("/auth", authRoutes);
router.use("/address", addressRoutes);
router.use("/cartype", cartypeRoutes);
router.use("/showcase", showcaseRoutes);
router.use("/user", userRoutes);
router.use("/service", serviceRoutes);
router.use("/addons", addonsRoutes);
router.use("/appsetting", appSettingRoutes);
router.use("/faq", faqRoutes);
router.use("/theme", themeRoutes);
router.use("/blog", blogRoutes);
router.use("/businesshour", businessHourRoutes);
router.use("/usertheme", userThemeRoutes);
router.use("/promocode", promoCodeRoutes);
router.use("/booking", bookingRoutes);
router.use("/review", reviewRoutes);
router.use("/dashbord", dashbordRoutes);
router.use("/content", contentRoutes);
router.use("/popupimage", popupimageRouter);

module.exports = router;
